---
title: "NCBI rentrenz walkthrough"
author: "Caleb Paslay"
date: "`r Sys.Date()`"
output: html_document
---

```{r echo=FALSE, message=FALSE}
library(tidyverse)
library(rentrez)
```

### What is the problem and the potential solution? 

**[AMV](https://www.ncbi.nlm.nih.gov/nuccore/?term=alfalfa+mosaic+virus)**

**[AMV complete](https://www.ncbi.nlm.nih.gov/nuccore/?term=alfalfa+mosaic+virus+complete)**


### Goals for this presentation
1. Introduction to terms used in rentrez to isolate various search parameters.
2. Plot the number of publications over time for a given topic. 

### Installation and loading 

Instalation of package "rentrez"

```install.packages("rentrez")``` 

Load the package rentrez

``` library(rentrez) ```

``` library(ggplot2) ```







entrez_dbs()

entrez_db_summary("nucleotide")

nucleotide_search <- entrez_search(db = "nucleotide", term = "ribosome")

View(nucleotide_search)

print(nucleotide_search)

nucleotide_search$ids

TYLCV <- entrez_search(db = "protein", term = "Tomato yellow leaf curl virus")

print(TYLCV)

TYLCV$ids

entrez_dbs()

r_search <- entrez_search(db="pubmed", term="R Language") 

r_search

r_search$ids

To increase the number of IDS we can do so by increasing the ret_max argument. 

another_r_search <- entrez_search(db="pubmed", term="R Language", retmax=40)

another_r_search

r_search$ids

another_r_search2 <- entrez_search(db="pubmed", term="R Language", retmax=60)

another_r_search2

another_r_search2$ids

To access all the IDs from the records, we can use NCBI's search term. 




#Here are some helpful links if you would like to investiage this package more!

[R markdown guide](https://bookdown.org/yihui/rmarkdown/)
[Rmarkdown hyperlinking](https://ucsbcarpentry.github.io/R-markdown/04-links-images-tables/index.html) 
[Entrez guidlines](https://cran.r-project.org/web/packages/rentrez/vignettes/rentrez_tutorial.html) 

