---
title: "Assignment 9: Heatmaps"
author: "Caleb Paslay"
date: "Last updated 9/14/2022"
output: html_document
---

**[my script](lecture_notes/lecture12_student_presentation.R)**

```{r message = FALSE}
library(ggplot2)
library(stats)
```

```{r fig.align='center'}
assignment <- read.csv("Data/MAH_assignment_data.csv")

View(assignment)

ggplot(assignment,
       aes(x = Sample, y = Gene, fill = Expression)) +
  geom_tile(colour = "black", size = 0.5) + 
  scale_fill_gradient(low = "black", high = "lightgreen") +
  theme_gray(base_size = 12) +
  facet_grid(~Tissue, switch = "x", scales = "free_x", space = "free_x") + 
  ggtitle(label = "Pheromone gene expression") +
  scale_x_discrete(labels = c('A.tri', 'D.brim', 'E.tyn M', 'E.tyn P', 'P.alb', 'R.kez', 
                            'A.tri', 'D.brim', 'E.tyn M', 'E.tyn P', 'P.alb', 'R.kez',
                            'A.tri', 'D.brim', 'E.tyn M', 'E.tyn P', 'P.alb', 'R.kez',
                            'A.tri', 'D.brim', 'E.tyn M', 'E.tyn P', 'P.alb', 'R.kez')) +
  theme(plot.title = element_text(face = "bold"),
        strip.placement = "outside", 
        legend.title = element_text(face = "bold"),
        axis.title = element_text(face = "bold"),
        axis.title.x = element_blank(),
        axis.text.y = element_text(color = "black"),
        axis.text.x = element_text(angle = 270, hjust = 0, color = "black"),
        axis.ticks = element_blank(),
        plot.background = element_blank(),
        panel.background = element_blank(),
        panel.border = element_blank())
```

